server:
  port: 8080

spring:
  application:
    name: kyc-mcp

  datasource:
    url: jdbc:postgresql://localhost:5432/kyc_db
    username: kyc_user
    password: kyc_password
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:db/changelog/db-changelog-master.sql
    enabled: true

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  ai:
    mcp:
      server:
        name: "kyc-mcp-server"
        version: "1.0.0"
        type: SYNC
        instructions: "KYC server for high-risk client management"
        sse-message-endpoint: /mcp/messages
        capabilities:
          tool: true

logging:
  level:
    com.theociobanoiu.kycmcp: DEBUG
    liquibase: INFO